name: Run Fuzzer on Push

# Run the workflow on every push to any branch
on:
  push:
    branches:
      - '**'

jobs:
  run-fuzzer:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin as the JDK distribution
          java-version: '21' # Or the Java version required for your project

      # Step 3: Grant execution permissions for html_parser
      - name: Make html_parser executable
        run: chmod +x ./html_parser_linux_x86_64

      # Step 4: Run the fuzzer
      - name: Run Fuzzer
        run: |
          javac Fuzzer.java # Compile the fuzzer
          java Fuzzer ./html_parser_linux_x86_64

          
      - name: Upload Failure Inputs
        if: ${{ failure() }} # Run only if the fuzzer exits with a non-zero status
        uses: actions/upload-artifact@v3
        with:
          name: failure_inputs
          path: failure_inputs.txt
